CREATE TABLE ADMINISTRADORES(
    USUARIO VARCHAR2(50) NOT NULL,
    CLAVE VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_ADMINISTRADORES PRIMARY KEY(USUARIO)
);

CREATE TABLE CLIENTE(
    RUT VARCHAR2(20) NOT NULL,
    NOMBRE VARCHAR2(50),
    APELLIDO VARCHAR2(50),
    DIRECCION VARCHAR2(100),
    TELEFONO VARCHAR2(10),
    NUM_COMPRAS INTEGER,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(CODIGO)
);

CREATE TABLE PRODUCTO(
    CODIGO VARCHAR2(100) NOT NULL,
    NOMBRE VARCHAR2(500),
    CATEGORIA VARCHAR2(100),
    STOCK NUMBER,
    STOCK_MIN NUMBER,
    PRECIO NUMBER,
    IMAGEN VARCHAR2(10),
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO)
);

CREATE TABLE PEDIDO(
    COD_PEDIDO VARCHAR2(100) NOT NULL,
    PRODUCTO VARCHAR2(100),
    CANTIDAD NUMBER,
    FECHA DATE,
    ESTADO VARCHAR2(10),
    DESCRIPCION VARCHAR2(500),
    CONSTRAINT PK_PEDIDO PRIMARY KEY(COD_PEDIDO),
    CONSTRAINT FK_PEDIDO_PRODUCTO FOREIGN KEY(PRODUCTO) REFERENCES PRODUCTO(CODIGO) ON DELETE CASCADE
);

CREATE TABLE VENTA(
    COD_VENTA VARCHAR2(100) NOT NULL,
    FECHA DATE,
    CLIENTE VARCHAR2(50),
    TOTAL_NETO NUMBER,
    IMPUESTO NUMBER,
    TOTAL NUMBER,
    CONSTRAINT PK_VENTA PRIMARY KEY(COD_VENTA),
    CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY(CLIENTE) REFERENCES CLIENTE(CODIGO) ON DELETE CASCADE
);

CREATE TABLE DETALLE_VENTA(
    COD_VENTA VARCHAR2(100) NOT NULL,
    NUM_LINEA INTEGER,
    PRODUCTO VARCHAR2(100),
    CANTIDAD NUMBER,
    PRECIO_UNIT NUMBER,
    TOTAL_LINEA NUMBER,
    CONSTRAINT PK_DETALLE PRIMARY KEY(COD_VENTA, NUM_LINEA),
    CONSTRAINT FK_DETALLE_PRODUCTO FOREIGN KEY(PRODUCTO) REFERENCES PRODUCTO(CODIGO) ON DELETE CASCADE,
    CONSTRAINT FK_DETALLE_VENTA FOREIGN KEY(COD_VENTA) REFERENCES VENTA(COD_VENTA) ON DELETE CASCADE
);

INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (1, 'HAMBURGESA DOBLE', 'HAMBURGESA', 100, 10, 4000, '1.jpg');
INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (2, 'HAMBURGESA DE TOCINO', 'HAMBURGESA', 100, 10, 3000, '2.jpg');
INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (3, 'HAMBURGESA REY', 'HAMBURGESA', 100, 10, 4000, '3.jpg');
INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (4, 'HAMBURGESA NEGRA', 'HAMBURGESA', 100, 10, 4000, '4.jpg');
INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (5, 'HAMBURGESA DE POLLO', 'HAMBURGESA', 100, 10, 3000, '5.jpg');
INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (6, 'HAMBURGESA DELUXE', 'HAMBURGESA', 100, 10, 5000, '6.jpg');

INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (7, 'PAPAS FRITAS', 'ACOMPAÑAMIENTO', 100, 10, 2000, '7.jpg');
INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (8, 'PAPAS FRITAS XL', 'ACOMPAÑAMIENTO', 100, 10, 4000, '8.jpg');
INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (9, 'ROLLITOS DE PRIMAVERA', 'ACOMPAÑAMIENTO', 100, 10, 5000, '9.jpg');
INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (10, 'PALITOS DE QUESO', 'ACOMPAÑAMIENTO', 100, 10, 5000, '10.jpg');
INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (11, 'NUGGETS', 'ACOMPAÑAMIENTO', 100, 10, 5000, '11.jpg');
INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (12, 'ARITOS DE CEBOLLA', 'ACOMPAÑAMIENTO', 100, 10, 3000, '12.jpg');

INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (13, 'COCA-COLA', 'BEBIDA', 100, 10, 1500, '13.jpg');
INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (14, 'FANTA', 'BEBIDA', 100, 10, 1500, '14.jpg');
INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (15, 'JUGO DE NARANJA Y LIMON', 'BEBIDA', 100, 10, 1500, '15.jpg');
INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (16, 'CERVEZA', 'BEBIDA', 100, 10, 2000, '16.jpg');
INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (17, 'JUGO FRUTOS ROJOS', 'BEBIDA', 100, 10, 2000, '17.jpg');
INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (18, 'WHISKY', 'BEBIDA', 100, 10, 3000, '18.jpg');

INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (19, 'TARTA DE LIMON', 'POSTRE', 100, 10, 3000, '19.jpg');
INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (20, 'CHEESECAKE DE FRAMBUESA', 'POSTRE', 100, 10, 3000, '20.jpg');
INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (21, 'VOLCAN DE CHOCOLATE', 'POSTRE', 100, 10, 4000, '21.jpg');
INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (22, 'BROWNIE DE CHOCOLATE', 'POSTRE', 100, 10, 4500, '22.jpg');
INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (23, 'PIE DE MANZANA', 'POSTRE', 100, 10, 4000, '23.jpg');
INSERT INTO PRODUCTO(CODIGO, NOMBRE, CATEGORIA, STOCK, STOCK_MIN, PRECIO, IMAGEN) VALUES (24, 'SUNDAE CHOCOLATE', 'POSTRE', 100, 10, 3000, '24.jpg');

INSERT INTO ADMINISTRADORES(USUARIO, CLAVE) VALUES ('OMOYA', 'FINIS');

COMMIT;

SELECT * FROM PRODUCTO;

SELECT * FROM ADMINISTRADORES;

DROP TABLE PRODUCTO;
DROP TABLE DETALLE_VENTA;
DROP TABLE VENTA;
DROP TABLE PEDIDO;
DROP TABLE CLIENTE;